--[[
  Name: MathParser.lua
  Author: ByteXenon [Luna Gilbert]
  Date: 2024-04-25
  ----------------
  Do not edit this file, this file is just
  a wrapper for the MathParser API.
--]]

local scriptPath, requirePath, localPath, oldPath
if not LUAXEN_PACKER then
  -- Localize the path, so this file can be run from anywhere
  scriptPath = (debug.getinfo(1).source:match("@?(.*/)") or "")
  requirePath = scriptPath .. "./?.lua"
  localPath = scriptPath .. "./"
  oldPath = package.path
  package.path = package.path .. ";" .. requirePath
end

local MathParser = require("src/MathParser")

if not LUAXEN_PACKER then
  -- Reset package.path
  package.path = oldPath
end

return MathParser
